

const articlesDB = [
    {
        img: "https://static3.srcdn.com/wordpress/wp-content/uploads/2021/09/MCU-repeated-Phase-2-Jane-foster-insult-What-if.jpg?q=50&fit=crop&w=960&h=500&dpr=1.5",
        title: "The MCU Just Repeated Phase 2’s Jane Foster Insult",
        about: [
                "Marvels What If...? episode 7 sees shield insult Dr. Jane Foster (Natalie Portman), a pattern first started in the MCU Phase 2. In What If... Thor Were An Only Child?, Jane and her intern, Darcy Lewis (Kat Dennings), sounds the alarm that the Earth is about to be invaded by aliens, although it turns out to be a still-worthy Thor (Chris Hemsworth) inviting the Marvel Cinematic Universes menagerie of cosmic beings to party on the third rock from the sun. Jane ends up looking foolish in S.H.I.E.L.D.s eyes as she becomes smitten with Thor, and What If...? marginalizes Dr. Foster once more in this alternate universe",
                "Introduced in Thor, Dr. Jane Foster is one of the world's leading astrophysicists, but her professional work usually takes a backseat to her status as the God of Thunder's girlfriend in MCU Phases 1 and 2. Jane and Thor are separated after the first film and she spends years pining for him while he helps form the Avengers and stops Loki's (Tom Hiddleston) Chitauri invasion. Jane and Thor are reunited when she is infected by the Aether in Thor: The Dark World and the Odinson brings Jane to Asgard to meet his parents. But Natalie Portman spent several years on the outs with Marvel Studios, which meant for all of MCU Phase 3, Jane was written out and Dr. Foster has no role in the Infinity Saga. Thor only fleetingly mentions his breakup with Jane in Thor: Ragnarok and Avengers: Endgame. But Natalie Portman agreed to make her MCU return and Jane will become the Goddess of Thunder in Thor: Love and Thunder. Portman and Marvel Studios being sympatico again also allowed the Academy Award-winner to voice Jane in What If...? episode 7.",
                "Jane and Darcy play comic relief roles in What If...? episode 7, which is itself a humorous romp inspired by Looney Tunes cartoons as Party Thor seeks to throw an epic rager on Midgard. Although S.H.I.E.L.D. does heed Dr. Foster's alarm about aliens storming Earth, once again, Jane's expertise as an astrophysicist is sidelined in What If...?, especially after Acting Director Maria Hill (Cobie Smulders) finds out Jane has been partying with Thor and even got matching tattoos with the Asgardian hunk. Jane does try to assert herself in a professional manner, but Hill and S.H.I.E.L.D. continue to disregard her point of view, putting their faith instead in Captain Marvel (Alexandra Daniels) and even a potential nuclear strike to put a stop to Thor and his world-breaking bash.",
                "Granted, Natalie Portman's comedy chops are underrated, and her rom-com chemistry with Chris Hemsworth was a major reason why the first Thor movie worked, but the pattern of Jane's scientific acumen being disregarded by S.H.I.E.L.D. is disconcerting. In Thor, S.H.I.E.L.D. and Agent Phil Coulson (Clark Gregg) treat Dr. Foster with incredible disrespect by stealing her equipment and attempting to silence her. Thor: The Dark World is even worse, with Jane basically being a mere plot device to move Thor's story forward. In What If...? Jane is again made to look silly and unprofessional, although Darcy's endless quips (though funny and endearing) don't help Dr. Foster's cause.",
                "So far, Marvel Studios hasn't been able (or hasn't attempted) to find a proper balance for Jane to be both Thor's love interest and a serious and respected scientist in her own right. Jane should have played a major role as an expert the Avengers turned to during their time travel escapade in Endgame had Portman and Marvel not been divided. Hopefully, Thor: Love and Thunder will be Dr. Jane Foster's MCU redemption in ways Marvel's What If...? wasn't. Along with turning Jane into Thor, the Goddess of Thunder, perhaps writer-director Taika Waititi will finally treat Jane as more than Thor's smitten love interest and properly present Jane Foster as one of the Marvel movies' top scientists as well."
               ],
        posted: "09/27/2021",
        author: "TIM HARRISON"
    },
    {
        img: "https://static1.srcdn.com/wordpress/wp-content/uploads/2021/09/craig-negga-macbeth.jpg?q=50&fit=crop&w=960&h=500&dpr=1.5",
        title: "Daniel Craig Post-Bond Role Will Be Macbeth With Ruth Negga",
        about: [
                "Daniel Craig's next post-Bond role will be at the lead in Shakespeare's Macbeth with Ruth Negga. Craig's last turn as Bond in the long-delayed No Time To Die is rolling out throughout the next month, sending the actor on a new career trajectory. Craig will next star in two more films in Rian Johnson's Knives Out franchise, once again playing investigator Benoit Blanc. He is also gearing up to star in director Todd Field's western thriller, The Creed of Violence. Ruth Negga was nominated for an Oscar for her performance in 2016's Loving and has appeared in multiple film/TV projects, including Warcraft, Agents of S.H.I.E.L.D. and AMC's Preacher.",
                "William Shakespeare's Macbeth aka The Tragedy of Macbeth was published in 1623 and follows a Scottish general (Macbeth), who receives a prophecy from three witches that he will become the King of Scotland, only to be driven to murder, madness, and betrayal in getting there. The play has been performed on stage and adapted for multiple forms for centuries, including a long list of film and TV adaptations. Some of the most recent include the Sam Worthington take, directed by Geoffrey Rush in 2006 and the 2015 version starring Michael Fassbender, directed by Justin Kurzel. The latest cinematic incarnation is the upcoming The Tragedy of Macbeth starring Denzel Washington and Frances McDormand, directed by Joel Coen.",
                "The next Broadway version of Macbeth has been announced, via Deadline, and will star the now former Bond Daniel Craig as Macbeth with Ruth Negga taking on the role of Lady Macbeth. The play will be directed by Tony Award winner, Sam Gold, with additional cast members to be announced at a later date. The play is expected to begin performances on Tuesday, March 29, 2022 at Broadway’s Lyceum Theatre, and will officially open on Thursday, April 28, 2022. A poster has already been released to promote the play, which can be seen below:",
                "The play is being produced by Bond's own Barbara Broccoli who says she's thrilled that Craig will be supporting the return of Broadway in the role, with Negga making her Broadway debut under the direction of Sam Gold. Gold formerly directed Craig in the off-Broadway production of Shakespeare's Othello in 2016. This also marks the return of Broadway after the Covid-19 pandemic forced the venue to be closed since March 2020.",
                "After playing Bond and working in additional film roles in-between since 2006, Craig can probably use the break from the pressure of carrying the 007 torch and dig into a play that will reunite him with more traditional acting. Macbeth is one of the most popular and sought after roles by actors, and Craig will surely deliver an amazing performance as the troubled Scottish general. Negga seems like an amazing fit for Lady Macbeth, and the duo will no doubt light up the stage with their presence in what will surely be one of the hottest tickets in town when Broadway opens the curtains to audiences once again next year. Tickets for Macbeth are expected to go on sale on October 8th.",
               ],
        posted: "09/16/2021",
        author: "BEN SHIREY"
    },
    {
        img: "https://static0.srcdn.com/wordpress/wp-content/uploads/2021/09/The-Suicide-Squad-behind-the-scenes-set-photo.jpg?q=50&fit=crop&w=960&h=500&dpr=1.5",
        title: "James Gunn Shares BTS Image Of The Suicide Squad Cast In Costume On Set",
        about: [
                "The Suicide Squad writer/director James Gunn shares a behind-the-scenes look at the cast in costume and on set. The Guardians of the Galaxy director's entry in the DCEU was released in theaters and on HBO Max this past summer on August 6. Though it largely disappointed at the box office, it is hard to blame the film itself given it was released in theaters amidst concerns about the COVID-19 Delta variant, coupled with its simultaneous streaming release and R-rating. In fact, The Suicide Squad was universally praised for vastly improving upon its 2016 predecessor.",
                "Gunn's version finds Amanda Waller (Viola Davis) assembling a new Task Force X team that also includes some characters from the previous Suicide Squad film, including Harley Quinn (Margot Robbie), Rick Flag (Joel Kinnaman), and Captain Boomerang (Jai Courtney). Some of the most notable newcomers include Bloodsport (Idris Elba), Peacemaker (John Cena), Ratcatcher 2 (Daniela Melchior), Polka-Dot Man (David Dastmalchian), and King Shark (Sylvester Stallone), while Waller uses the rest of the team as cannon fodder in the mission to destroy Project Starfish.",
                "Now, writer/director James Gunn is sharing a behind-the-scenes look at The Suicide Squad cast on set and in costume as they wait for setup in between takes. Gunn shared the photo on his incredibly active Twitter page. Pictured from left to right are Elba, Melchior, Robbie, and Dastmalchian, whose characters were the last Task Force X members remaining (along with Stallone's King Shark) after they destroyed the Nazi-era laboratory known as Jötunheim. Check out the photo below:",
                "Even though The Suicide Squad was released nearly two months ago, Gunn's Twitter page has been a gift that keeps on giving content related to the film. Just this month, he has shared a BTS video of Harley Quinn and Polka-Dot Man flying through the air on cables, confirmed a Toxic Avenger easter egg, and revealed what scene was hardest to cut. The Suicide Squad's gag reel was also a welcome surprise, which seemed to go hand-in-hand with the film's zany appeal.",
                "Now that The Suicide Squad is no longer playing in theaters or streaming on HBO Max, fans are looking ahead to the Peacemaker spinoff series, which will continue James Gunn's tenure with DC for the time being. Though Peacemaker was presumed dead after Bloodsport shot him in the throat, a post-credits scene revealed he was still alive. There have been a few brief looks at Cena's spinoff series so far, so stay tuned to Gunn's Twitter page for updates on all things related to The Suicide Squad and the upcoming Peacemaker series.",
               ],
        posted: "09/13/2021",
        author: "BEN SHIREY"
    },
    {
        img: "https://static2.srcdn.com/wordpress/wp-content/uploads/2021/07/George-R-Romero-Unmade-Goosebumps-Zombie-Movie-welcome-to-dead-house-.jpg?q=50&fit=crop&w=960&h=500&dpr=1.5",
        title: "George Romero's Unmade Goosebumps Zombie Movie Explained",
        about: [
                "George Romero was once attached to direct a Goosebumps adaptation involving zombies – here’s what the story would have been about. Romero, who sadly passed away in 2017, is renowned for his work in the horror genre. Released in 1968, Night of the Living Dead provoked controversy for terrifying young viewers but instantly became a landmark film, criticizing 1960s American politics and launching a franchise that remains the benchmark for all zombie films.",
                "Goosebumps is similarly praised within the realm of horror, albeit for the franchise’s ability to encourage children’s interest in reading. Author R.L. Stine published 62 books between 1992-1997, while a television series based on the books debuted in 1995. The horror anthology boasted a multitude of creative monsters and was eventually turned into a feature film, released in 2015 as a meta horror-comedy starring Jack Black as Stine. However, there were already plans for a movie nearly 20 years beforehand.",
                "In the late 1990s, George Romero planned to direct Welcome to Dead House, the very first novel in the Goosebumps book series. The novel tells the story of the Benson family, who move to the mysterious town of Dark Falls, only to discover the town’s residents are all undead. Given Romero’s success in the zombie subgenre, it makes perfect sense he would want to be chosen to adapt the story. The main character names and basic premise would have remained the same, but Romero planned to add his own spin on the story to provide deeper social commentary on contemporary American capitalism.",
                "The adaptation would have followed Stine’s plot of Dark Falls’ townspeople luring a family into their midst to feed off them, thereby sustaining their immortality for another year. In Stine’s book, the catalyst for a humans' transformation into zombies was escaped gas from a local factory. In contrast, Romero altered the origin to the dead town leader, Foster Devries, possessing Dark Falls and pulling the strings with his supernatural powers like a zombie dictator. With small-town America hiding a dark secret and the undead crumbling to dust when hit with the beam of a flashlight, the story would have enabled Romero to utilize creeping tension and neighborly paranoia within classic US suburbia, while finding new ways to visualize zombie effects. Romero was already developing a similar project in the 1980s called Apartment Living, except that movie's sentient home was reworked to possession involving a town patriarch.",
                "Romero knew how to instill fear by turning everyday life into terrifying commentary on society. His zombies were to be trapped in a kind of dead-end job, the adults searching for victims while their undead children question their loss of innocence. In Stine’s Goosebumps book, the Bensons' merely feared death. Romero took the horror further by threatening victims with resurrection as slaves of Dark Falls, unable to leave and forced to repeat the same cycle of murder. The capitalist themes became more overt, with the town’s residents reliant on following Devries’ orders to survive. Romero was interested in the loss of free will and oppressive American culture; Dawn of the Dead (1978), for instance, used its shopping mall setting as an allegory for mindless consumerism. Welcome to Dead House would have shifted focus to small towns’ dependence on local business, with immortality the new form of currency.",
               ],
        posted: "09/12/2021",
        author: "LISA RAVEN"    
    },
    
]

export default  articlesDB;


// {
//     img: "",
//     title: "",
//     about: [
//             "",
//             "",
//             "",
//             "",
//             "",
//            ],
//     posted: "",
//     author: ""
// },